In [1]:
import pandas as pd
print(pd.__version__)

2.2.3

In [2]:
import sqlite3
import pandas as pd
con=sqlite3.connect(r'C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\data\raw\ipl.db')

def q(sql):
    return pd.read_sql(sql,con)

In [3]:
def run_sql_file(path):
    with open(path,'r') as f:
        script=f.read()
        con.executescript(script)
        con.commit()
        print('ran',path)

In [4]:
run_sql_file('C:\\Users\\BCA\\Documents\\Sem 3\\OJT\\Project 3.1\\sql\\practice\\test.sql')

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\test.sql

In [5]:
run_sql_file('../sql/practice/01_nulls_and_blanks.sql')

ran ../sql/practice/01_nulls_and_blanks.sql

In [6]:
q("""select count (*) as blank_before
from deliveries
where trim(bowler_type)=''""")

   blank_before
0             8

In [7]:
q("""select count (*) as null_after
from v_players_clean
where field_pos_clean is null""")

   null_after
0         700

In [8]:
run_sql_file(r'C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\02_merge_categories.sql')

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\02_merge_categories.sql

In [9]:
q("""select distinct team_name
from teams
order by team_name;""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [10]:
q("""SELECT DISTINCT team_name_clean
FROM v_teams_clean
ORDER BY team_name_clean;
""")

                team_name_clean
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13  Royal Challengers Bangalore
14          Sunrisers Hyderabad

In [11]:
run_sql_file(r"C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\03_venue_names.sql")

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\03_venue_names.sql

In [12]:
q("""SELECT venue,COUNT(*) AS matches
FROM matches
WHERE venue IN ('Wankhede Stadium','Wankhede Stadium, Mumbai')
GROUP BY venue;""")

                      venue  matches
0          Wankhede Stadium       73
1  Wankhede Stadium, Mumbai       57

In [13]:
q("""SELECT venue, COUNT(*) AS matches
FROM matches
GROUP BY venue
ORDER BY matches DESC
LIMIT 5;""")

                      venue  matches
0              Eden Gardens       77
1          Wankhede Stadium       73
2     M Chinnaswamy Stadium       65
3          Feroz Shah Kotla       60
4  Wankhede Stadium, Mumbai       57

In [14]:
q("""select venue_clean, COUNT(*) AS matches
from v_matches_venue
group by venue_clean
order by matches desc
limit 5;""")

                          venue_clean  matches
0                    Wankhede Stadium      130
1                        Eden Gardens      104
2              MA Chidambaram Stadium       95
3               M Chinnaswamy Stadium       89
4  Rajiv Gandhi International Stadium       87

In [15]:
q("""select count(*) as rows, count(distinct venue) as names from venues;""")

   rows  names
0    63     59

In [16]:
q("""SELECT venue_clean,COUNT(*) AS matches
FROM  v_matches_venue
GROUP BY venue_clean
ORDER BY matches DESC LIMIT 5;""")

                          venue_clean  matches
0                    Wankhede Stadium      130
1                        Eden Gardens      104
2              MA Chidambaram Stadium       95
3               M Chinnaswamy Stadium       89
4  Rajiv Gandhi International Stadium       87

In [17]:
run_sql_file(r"C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\04_dedupe_venues.sql")

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\04_dedupe_venues.sql

In [18]:
q("""SELECT COUNT(*) AS rows,COUNT(DISTINCT venue) AS names
FROM v_venues_clean;""")

   rows  names
0    59     59

In [19]:
q("""SELECT COUNT(*) AS count, venue, city
FROM v_venues_clean
GROUP BY venue
ORDER BY COUNT(*) DESC;""")

    count                                              venue            city
0       1                   Zayed Cricket Stadium, Abu Dhabi       Abu Dhabi
1       1                           Wankhede Stadium, Mumbai          Mumbai
2       1                                   Wankhede Stadium          Mumbai
3       1       Vidarbha Cricket Association Stadium, Jamtha          Nagpur
4       1                                    SuperSport Park       Centurion
5       1                         Subrata Roy Sahara Stadium            Pune
6       1                                   St George's Park  Port Elizabeth
7       1                               Sheikh Zayed Stadium       Abu Dhabi
8       1                            Sharjah Cricket Stadium         Sharjah
9       1   Shaheed Veer Narayan Singh International Stadium          Raipur
10      1                     Sawai Mansingh Stadium, Jaipur          Jaipur
11      1                             Sawai Mansingh Stadium          Jaipur
12      1             Saurashtra Cricket Association Stadium          Rajkot
13      1                       Sardar Patel Stadium, Motera       Ahmedabad
14      1  Rajiv Gandhi International Stadium, Uppal, Hyd...       Hyderabad
15      1          Rajiv Gandhi International Stadium, Uppal       Hyderabad
16      1                 Rajiv Gandhi International Stadium       Hyderabad
17      1         Punjab Cricket Association Stadium, Mohali      Chandigarh
18      1  Punjab Cricket Association IS Bindra Stadium, ...      Chandigarh
19      1  Punjab Cricket Association IS Bindra Stadium, ...      Chandigarh
20      1       Punjab Cricket Association IS Bindra Stadium      Chandigarh
21      1                                    OUTsurance Oval    Bloemfontein
22      1                                           Newlands       Cape Town
23      1                              New Wanderers Stadium    Johannesburg
24      1                                      Nehru Stadium           Kochi
25      1                   Narendra Modi Stadium, Ahmedabad       Ahmedabad
26      1      Maharashtra Cricket Association Stadium, Pune            Pune
27      1            Maharashtra Cricket Association Stadium            Pune
28      1  Maharaja Yadavindra Singh International Cricke...  New Chandigarh
29      1  Maharaja Yadavindra Singh International Cricke...          Mohali
30      1           MA Chidambaram Stadium, Chepauk, Chennai         Chennai
31      1                    MA Chidambaram Stadium, Chepauk         Chennai
32      1                             MA Chidambaram Stadium         Chennai
33      1                              M.Chinnaswamy Stadium       Bengaluru
34      1                   M Chinnaswamy Stadium, Bengaluru       Bengaluru
35      1                              M Chinnaswamy Stadium       Bangalore
36      1                                          Kingsmead          Durban
37      1                 JSCA International Stadium Complex          Ranchi
38      1                             Holkar Cricket Stadium          Indore
39      1  Himachal Pradesh Cricket Association Stadium, ...      Dharamsala
40      1       Himachal Pradesh Cricket Association Stadium      Dharamsala
41      1                                         Green Park          Kanpur
42      1                                   Feroz Shah Kotla           Delhi
43      1                              Eden Gardens, Kolkata         Kolkata
44      1                                       Eden Gardens         Kolkata
45      1                Dubai International Cricket Stadium           Dubai
46      1  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...   Visakhapatnam
47      1  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...   Visakhapatnam
48      1                 Dr DY Patil Sports Academy, Mumbai          Mumbai
49      1                         Dr DY Patil Sports Academy          Mumbai
50      1                              De Beers Diamond Oval       Kimberley
51      1                                       Buffalo Park     East London
52      1                          Brabourne Stadium, Mumbai          Mumbai
53      1                                  Brabourne Stadium          Mumbai
54      1  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...         Lucknow
55      1                Barsapara Cricket Stadium, Guwahati        Guwahati
56      1                                   Barabati Stadium         Cuttack
57      1                        Arun Jaitley Stadium, Delhi           Delhi
58      1                               Arun Jaitley Stadium           Delhi

In [20]:
run_sql_file(r"C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\05_city_fallback.sql")

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\05_city_fallback.sql

In [21]:
q("""SELECT venue,COUNT(*) AS no_city
FROM matches
WHERE city IS NULL
GROUP BY venue;
""")

                                 venue  no_city
0  Dubai International Cricket Stadium       33
1              Sharjah Cricket Stadium       18

In [22]:
q("""
SELECT city_clean
FROM v_city_clean
WHERE city_clean IS NULL;
""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [23]:
q("""select city_clean from v_city_clean where city_clean = 'Unknown'""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [24]:
q("""
SELECT city_clean
FROM v_city_clean
WHERE city_clean IS NULL;
""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [25]:
q("""
SELECT city_clean
FROM v_city_clean;
""")

          city_clean
0          Bangalore
1          Hyderabad
2               Pune
3             Rajkot
4             Indore
...              ...
1207           Delhi
1208  New Chandigarh
1209          Mumbai
1210       Ahmedabad
1211          Jaipur

[1212 rows x 1 columns]

In [26]:
run_sql_file(r"C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\06_season_year.sql")

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\06_season_year.sql

In [27]:
q("""select venue, count(*) as no_city from matches where city is null group by venue;""")

                                 venue  no_city
0  Dubai International Cricket Stadium       33
1              Sharjah Cricket Stadium       18

In [28]:
q("""SELECT season, COUNT(*) AS matches
FROM matches
WHERE season ='2020/21' 
GROUP BY season;
""")

    season  matches
0  2020/21       60

In [29]:
  q("""select distinct season, season_year from v_season where season = '2020/21'""")

    season  season_year
0  2020/21         2020

In [30]:
run_sql_file(r"C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\07_win_definition.sql")

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\07_win_definition.sql

In [31]:
run_sql_file(r"C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\08_matches_clean.sql")

ran C:\Users\BCA\Documents\Sem 3\OJT\Project 3.1\sql\practice\08_matches_clean.sql

In [32]:
q("""select * from matches_clean;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,field
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,field
...,...,...,...,...,...,...,...,...
1207,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,field
1208,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,field
1209,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,bat
1210,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,field
1211,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,bat

In [33]:
import ast
import pandas as pd
d = pd.read_sql('select * from deliveries where  fielders_involved is not null', con)
d['fielders'] = d['fielders_involved'].apply(ast.literal_eval)

d = d.explode('fielders')

d['fielders'].value_counts().head(5)

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
Name: count, dtype: int64