In [1]:
import sqlite3
import pandas as pd

con = sqlite3.connect('../data/raw/ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [2]:
q("""select * from matches;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [3]:
q("""select * from deliveries;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,1,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals

In [4]:
q("""select * from teams;""")

    team_id                    team_name
0         1  Royal Challengers Bangalore
1         2          Sunrisers Hyderabad
2         3               Mumbai Indians
3         4       Rising Pune Supergiant
4         5                Gujarat Lions
5         6        Kolkata Knight Riders
6       129          Chennai Super Kings
7       134             Rajasthan Royals
8       252               Delhi Capitals
9       494                 Punjab Kings
10      614         Lucknow Super Giants
11      615               Gujarat Titans
12     1068              Deccan Chargers
13     1414         Kochi Tuskers Kerala
14     1419                Pune Warriors
15     3604      Rising Pune Supergiants

In [5]:
q("""select * from players;""")

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name
0,963,MN Samuels,Right hand Bat,Right arm Offbreak,,Marlon Nathaniel Samuels
1,53,SB Jakati,Left hand Bat,Slow Left arm Orthodox,,Shadab Bashir Jakati
2,12,DA Warner,Left hand Bat,Legbreak,,David Andrew Warner
3,268,RA Tripathi,Right hand Bat,Right arm Medium,,Rahul Ajay Tripathi
4,186,S Nadeem,Right hand Bat,Slow Left arm Orthodox,,Shahbaz Nadeem
...,...,...,...,...,...,...
794,8475,Suyash Sharma,Right hand Bat,Legbreak Googly,,Suyash Sharma
795,45004,D Madushanka,Right hand Bat,Right arm Medium fast,NaN,K Dasun Madusanka
796,42566,V Suryavanshi,Left hand Bat,Slow Left arm Orthodox,NaN,Vaibhav Suryavanshi
797,26,N Rana,Left hand Bat,"Right arm Medium, Right arm Offbreak, Legbreak",,Nitish Rana
798,45986,SU Parakh,Left hand Bat,Legbreak,NaN,Sahil Ulhas Parakh

In [6]:
q("""select * from venues;""")

,venue_id,venue,city
0,1,M Chinnaswamy Stadium,Bangalore
1,2,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,3,Maharashtra Cricket Association Stadium,Pune
3,4,Saurashtra Cricket Association Stadium,Rajkot
4,5,Holkar Cricket Stadium,Indore
...,...,...,...
58,59,Subrata Roy Sahara Stadium,Pune
59,60,Shaheed Veer Narayan Singh International Stadium,Raipur
60,61,JSCA International Stadium Complex,Ranchi
61,62,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
62,63,Maharaja Yadavindra Singh International Cricke...,New Chandigarh

In [7]:
q("""select * from matches limit 5;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0

In [8]:
q("""select match_id,city,venue from matches limit 15;""")

    match_id       city                                      venue
0     335982  Bangalore                      M Chinnaswamy Stadium
1    1082591  Hyderabad  Rajiv Gandhi International Stadium, Uppal
2    1082592       Pune    Maharashtra Cricket Association Stadium
3    1082593     Rajkot     Saurashtra Cricket Association Stadium
4    1082594     Indore                     Holkar Cricket Stadium
5    1082595  Bengaluru                      M.Chinnaswamy Stadium
6    1082596  Hyderabad  Rajiv Gandhi International Stadium, Uppal
7    1082597     Mumbai                           Wankhede Stadium
8    1082598     Indore                     Holkar Cricket Stadium
9    1082599       Pune    Maharashtra Cricket Association Stadium
10   1082600     Mumbai                           Wankhede Stadium
11   1082601    Kolkata                               Eden Gardens
12   1082602  Bangalore                      M Chinnaswamy Stadium
13   1082603     Rajkot     Saurashtra Cricket Association Stadium
14   1082604    Kolkata                               Eden Gardens

In [9]:
q("""select batter,bowler from deliveries limit 5;""")

        batter   bowler
0   SC Ganguly  P Kumar
1  BB McCullum  P Kumar
2  BB McCullum  P Kumar
3  BB McCullum  P Kumar
4  BB McCullum  P Kumar

In [10]:
q("""select distinct batsman_type from deliveries;""")

     batsman_type
0   Left hand Bat
1  Right hand Bat
2             NaN

In [11]:
q("""select distinct bowler_type from deliveries;""")

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [12]:
q("""select distinct player_full_name from players;""")

             player_full_name
0    Marlon Nathaniel Samuels
1        Shadab Bashir Jakati
2         David Andrew Warner
3         Rahul Ajay Tripathi
4              Shahbaz Nadeem
..                        ...
794             Suyash Sharma
795         K Dasun Madusanka
796       Vaibhav Suryavanshi
797               Nitish Rana
798        Sahil Ulhas Parakh

[799 rows x 1 columns]

In [13]:
q("""select match_id,season_id,city,match_winner from matches where match_winner="Chennai Super Kings";""")

     match_id  season_id       city         match_winner
0     1136561       2018     Mumbai  Chennai Super Kings
1     1136565       2018    Chennai  Chennai Super Kings
2     1136577       2018       Pune  Chennai Super Kings
3     1136580       2018  Hyderabad  Chennai Super Kings
4     1136584       2018  Bengaluru  Chennai Super Kings
..        ...        ...        ...                  ...
141   1473494       2025    Kolkata  Chennai Super Kings
142   1473504       2025  Ahmedabad  Chennai Super Kings
143   1527691       2026    Chennai  Chennai Super Kings
144   1529265       2026    Chennai  Chennai Super Kings
145   1529276       2026     Mumbai  Chennai Super Kings

[146 rows x 4 columns]

In [14]:
q("""select match_id,season,city,venue from matches where season >= 2015;""")

,match_id,season,city,venue
0,829705,2015,Kolkata,Eden Gardens
1,829707,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
2,829709,2015,Pune,Maharashtra Cricket Association Stadium
3,829711,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
4,829713,2015,Kolkata,Eden Gardens
...,...,...,...,...
749,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
750,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
751,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
752,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
753,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [15]:
q("""select match_id,season,city,venue from matches where season <= 2015;""")

     match_id season        city                                       venue
0      335982   2008   Bangalore                       M Chinnaswamy Stadium
1      335983   2008  Chandigarh  Punjab Cricket Association Stadium, Mohali
2      335984   2008       Delhi                            Feroz Shah Kotla
3      335985   2008      Mumbai                            Wankhede Stadium
4      335986   2008     Kolkata                                Eden Gardens
..        ...    ...         ...                                         ...
512    829815   2015   Hyderabad   Rajiv Gandhi International Stadium, Uppal
513    829817   2015      Mumbai                            Wankhede Stadium
514    829819   2015        Pune     Maharashtra Cricket Association Stadium
515    829821   2015      Ranchi          JSCA International Stadium Complex
516    829823   2015     Kolkata                                Eden Gardens

[517 rows x 4 columns]

In [16]:
q("""select match_id,season,city,venue from matches where season >= 2015 and city="Bangalore";""")

    match_id season       city                  venue
0     829719   2015  Bangalore  M Chinnaswamy Stadium
1     829737   2015  Bangalore  M Chinnaswamy Stadium
2     829745   2015  Bangalore  M Chinnaswamy Stadium
3     829763   2015  Bangalore  M Chinnaswamy Stadium
4     829771   2015  Bangalore  M Chinnaswamy Stadium
5     829785   2015  Bangalore  M Chinnaswamy Stadium
6     829813   2015  Bangalore  M Chinnaswamy Stadium
7     980907   2016  Bangalore  M Chinnaswamy Stadium
8     980921   2016  Bangalore  M Chinnaswamy Stadium
9     980959   2016  Bangalore  M Chinnaswamy Stadium
10    980969   2016  Bangalore  M Chinnaswamy Stadium
11    980981   2016  Bangalore  M Chinnaswamy Stadium
12    980987   2016  Bangalore  M Chinnaswamy Stadium
13    980999   2016  Bangalore  M Chinnaswamy Stadium
14    981013   2016  Bangalore  M Chinnaswamy Stadium
15    981019   2016  Bangalore  M Chinnaswamy Stadium
16   1082602   2017  Bangalore  M Chinnaswamy Stadium
17   1082607   2017  Bangalore  M Chinnaswamy Stadium
18   1082621   2017  Bangalore  M Chinnaswamy Stadium
19   1082633   2017  Bangalore  M Chinnaswamy Stadium
20   1082636   2017  Bangalore  M Chinnaswamy Stadium
21   1082648   2017  Bangalore  M Chinnaswamy Stadium
22   1082649   2017  Bangalore  M Chinnaswamy Stadium

In [17]:
q("""select match_id,season,city,venue from matches where season >= 2015 or city="Bangalore";""")

,match_id,season,city,venue
0,335982,2008,Bangalore,M Chinnaswamy Stadium
1,1082591,2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,1082592,2017,Pune,Maharashtra Cricket Association Stadium
3,1082593,2017,Rajkot,Saurashtra Cricket Association Stadium
4,1082594,2017,Indore,Holkar Cricket Stadium
...,...,...,...,...
791,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
792,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
793,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
794,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
795,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [18]:
q("""select match_id,season_id,city,match_winner from matches where season_id >= 2010 and match_winner="Royal Challengers Bangalore";""")

     match_id  season_id       city                 match_winner
0     1082595       2017  Bengaluru  Royal Challengers Bangalore
1     1082610       2017     Rajkot  Royal Challengers Bangalore
2     1082646       2017      Delhi  Royal Challengers Bangalore
3     1136568       2018  Bengaluru  Royal Challengers Bangalore
4     1136579       2018  Bengaluru  Royal Challengers Bangalore
..        ...        ...        ...                          ...
121   1527684       2026  Bengaluru  Royal Challengers Bangalore
122   1527693       2026     Mumbai  Royal Challengers Bangalore
123   1529266       2026  Bengaluru  Royal Challengers Bangalore
124   1529277       2026  Bengaluru  Royal Challengers Bangalore
125   1529282       2026      Delhi  Royal Challengers Bangalore

[126 rows x 4 columns]

In [19]:
q("select count(*) from matches;")

   count(*)
0      1212

In [20]:
q("select count(*) As matches from matches;")

   matches
0     1212

In [21]:
q("select count (*) As deliveries from deliveries;")

   deliveries
0      288226

In [22]:
q("select count (*) As teams from teams;")

   teams
0     16

In [23]:
q("select count (*) As players from players;")

   players
0      799

In [24]:
q("select count (*) As venues from venues;")

   venues
0      63

In [25]:
q("select venue,count(*) As Matches from matches Group by venue;")

                                                venue  Matches
0                                Arun Jaitley Stadium       14
1                         Arun Jaitley Stadium, Delhi       27
2                                    Barabati Stadium        7
3                 Barsapara Cricket Stadium, Guwahati        8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
5                                   Brabourne Stadium       10
6                           Brabourne Stadium, Mumbai       17
7                                        Buffalo Park        3
8                               De Beers Diamond Oval        3
9                          Dr DY Patil Sports Academy       17
10                 Dr DY Patil Sports Academy, Mumbai       20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
13                Dubai International Cricket Stadium       46
14                                       Eden Gardens       77
15                              Eden Gardens, Kolkata       27
16                                   Feroz Shah Kotla       60
17                                         Green Park        4
18       Himachal Pradesh Cricket Association Stadium        9
19  Himachal Pradesh Cricket Association Stadium, ...        6
20                             Holkar Cricket Stadium        9
21                 JSCA International Stadium Complex        7
22                                          Kingsmead       15
23                              M Chinnaswamy Stadium       65
24                   M Chinnaswamy Stadium, Bengaluru       24
25                              M.Chinnaswamy Stadium       15
26                             MA Chidambaram Stadium        9
27                    MA Chidambaram Stadium, Chepauk       48
28           MA Chidambaram Stadium, Chepauk, Chennai       38
29  Maharaja Yadavindra Singh International Cricke...       10
30  Maharaja Yadavindra Singh International Cricke...        5
31            Maharashtra Cricket Association Stadium       22
32      Maharashtra Cricket Association Stadium, Pune       13
33                   Narendra Modi Stadium, Ahmedabad       37
34                                      Nehru Stadium        5
35                              New Wanderers Stadium        8
36                                           Newlands        7
37                                    OUTsurance Oval        2
38       Punjab Cricket Association IS Bindra Stadium       10
39  Punjab Cricket Association IS Bindra Stadium, ...       11
40  Punjab Cricket Association IS Bindra Stadium, ...        5
41         Punjab Cricket Association Stadium, Mohali       35
42                 Rajiv Gandhi International Stadium       15
43          Rajiv Gandhi International Stadium, Uppal       49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
45                       Sardar Patel Stadium, Motera       12
46             Saurashtra Cricket Association Stadium       10
47                             Sawai Mansingh Stadium       47
48                     Sawai Mansingh Stadium, Jaipur       19
49   Shaheed Veer Narayan Singh International Stadium        6
50                            Sharjah Cricket Stadium       28
51                               Sheikh Zayed Stadium       29
52                                   St George's Park        7
53                         Subrata Roy Sahara Stadium       16
54                                    SuperSport Park       12
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                                   Wankhede Stadium       73
57                           Wankhede Stadium, Mumbai       57
58                   Zayed Cricket Stadium, Abu Dhabi        8

In [26]:
q("select match_winner,count(*) As Winner from matches Group by match_winner Order by Winner DESC;")

                   match_winner  Winner
0                Mumbai Indians     155
1           Chennai Super Kings     146
2   Royal Challengers Bangalore     139
3         Kolkata Knight Riders     137
4           Sunrisers Hyderabad     132
5                  Punjab Kings     130
6                Delhi Capitals     126
7              Rajasthan Royals     125
8                Gujarat Titans      42
9          Lucknow Super Giants      33
10       Rising Pune Supergiant      15
11                Pune Warriors      13
12                Gujarat Lions      13
13         Kochi Tuskers Kerala       6

In [27]:
q("Select match_winner,count(*) As Winner from matches Group by match_winner having Winner >= 100 order by Winner DESC;")

                  match_winner  Winner
0               Mumbai Indians     155
1          Chennai Super Kings     146
2  Royal Challengers Bangalore     139
3        Kolkata Knight Riders     137
4          Sunrisers Hyderabad     132
5                 Punjab Kings     130
6               Delhi Capitals     126
7             Rajasthan Royals     125

In [28]:
q("Select bowler,count(*) As BALLS from deliveries Group by bowler having count(*) >= 1000 order by BALLS DESC;")

          bowler  BALLS
0       R Ashwin   4868
1        B Kumar   4596
2      SP Narine   4586
3      RA Jadeja   4261
4      YS Chahal   4068
..           ...    ...
81      VR Aaron   1065
82    GJ Maxwell   1047
83  JR Hazlewood   1035
84    Noor Ahmad   1008
85       S Gopal   1000

[86 rows x 2 columns]

In [29]:
q("Select count(*) AS Nullvalues from matches where city is NULL;")

   Nullvalues
0          51

In [30]:
q("Select count(*) AS Nullvalues from matches where city is not NULL;")

   Nullvalues
0        1161

In [31]:
q("Select count(*) AS Winbyruns from matches where win_by_runs is not NULL;")

   Winbyruns
0        546

In [32]:
q("Select match_winner,count(*) AS Winbyruns from matches where win_by_runs is not NULL Group by match_winner;")

                   match_winner  Winbyruns
0           Chennai Super Kings         75
1                Delhi Capitals         47
2                 Gujarat Lions          1
3                Gujarat Titans         16
4          Kochi Tuskers Kerala          2
5         Kolkata Knight Riders         57
6          Lucknow Super Giants         20
7                Mumbai Indians         77
8                 Pune Warriors          6
9                  Punjab Kings         57
10             Rajasthan Royals         48
11       Rising Pune Supergiant          7
12  Royal Challengers Bangalore         64
13          Sunrisers Hyderabad         69

In [33]:
q("select lower(batter) from deliveries;")

         lower(batter)
0       a ashish reddy
1       a ashish reddy
2       a ashish reddy
3       a ashish reddy
4       a ashish reddy
...                ...
288221          z khan
288222          z khan
288223          z khan
288224          z khan
288225          z khan

[288226 rows x 1 columns]

In [34]:
q("select trim(batter) from deliveries;")

          trim(batter)
0       A Ashish Reddy
1       A Ashish Reddy
2       A Ashish Reddy
3       A Ashish Reddy
4       A Ashish Reddy
...                ...
288221          Z Khan
288222          Z Khan
288223          Z Khan
288224          Z Khan
288225          Z Khan

[288226 rows x 1 columns]

In [35]:
q("select city,length(city) from venues;")

              city  length(city)
0        Bangalore           9.0
1        Hyderabad           9.0
2             Pune           4.0
3           Rajkot           6.0
4           Indore           6.0
..             ...           ...
58            Pune           4.0
59          Raipur           6.0
60          Ranchi           6.0
61  New Chandigarh          14.0
62  New Chandigarh          14.0

[63 rows x 2 columns]

In [36]:
q("select match_winner,case when win_by_runs is null then 'win_by_wickets' else 'win_by_runs' end as winning_type from matches;")

                     match_winner    winning_type
0           Kolkata Knight Riders     win_by_runs
1             Sunrisers Hyderabad     win_by_runs
2          Rising Pune Supergiant  win_by_wickets
3           Kolkata Knight Riders  win_by_wickets
4                    Punjab Kings  win_by_wickets
...                           ...             ...
1207  Royal Challengers Bangalore  win_by_wickets
1208             Rajasthan Royals  win_by_wickets
1209          Sunrisers Hyderabad  win_by_wickets
1210               Gujarat Titans  win_by_wickets
1211               Delhi Capitals  win_by_wickets

[1212 rows x 2 columns]

In [37]:
q("select venue, count(*) As matches from matches group by venue;")

                                                venue  matches
0                                Arun Jaitley Stadium       14
1                         Arun Jaitley Stadium, Delhi       27
2                                    Barabati Stadium        7
3                 Barsapara Cricket Stadium, Guwahati        8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
5                                   Brabourne Stadium       10
6                           Brabourne Stadium, Mumbai       17
7                                        Buffalo Park        3
8                               De Beers Diamond Oval        3
9                          Dr DY Patil Sports Academy       17
10                 Dr DY Patil Sports Academy, Mumbai       20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
13                Dubai International Cricket Stadium       46
14                                       Eden Gardens       77
15                              Eden Gardens, Kolkata       27
16                                   Feroz Shah Kotla       60
17                                         Green Park        4
18       Himachal Pradesh Cricket Association Stadium        9
19  Himachal Pradesh Cricket Association Stadium, ...        6
20                             Holkar Cricket Stadium        9
21                 JSCA International Stadium Complex        7
22                                          Kingsmead       15
23                              M Chinnaswamy Stadium       65
24                   M Chinnaswamy Stadium, Bengaluru       24
25                              M.Chinnaswamy Stadium       15
26                             MA Chidambaram Stadium        9
27                    MA Chidambaram Stadium, Chepauk       48
28           MA Chidambaram Stadium, Chepauk, Chennai       38
29  Maharaja Yadavindra Singh International Cricke...       10
30  Maharaja Yadavindra Singh International Cricke...        5
31            Maharashtra Cricket Association Stadium       22
32      Maharashtra Cricket Association Stadium, Pune       13
33                   Narendra Modi Stadium, Ahmedabad       37
34                                      Nehru Stadium        5
35                              New Wanderers Stadium        8
36                                           Newlands        7
37                                    OUTsurance Oval        2
38       Punjab Cricket Association IS Bindra Stadium       10
39  Punjab Cricket Association IS Bindra Stadium, ...       11
40  Punjab Cricket Association IS Bindra Stadium, ...        5
41         Punjab Cricket Association Stadium, Mohali       35
42                 Rajiv Gandhi International Stadium       15
43          Rajiv Gandhi International Stadium, Uppal       49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
45                       Sardar Patel Stadium, Motera       12
46             Saurashtra Cricket Association Stadium       10
47                             Sawai Mansingh Stadium       47
48                     Sawai Mansingh Stadium, Jaipur       19
49   Shaheed Veer Narayan Singh International Stadium        6
50                            Sharjah Cricket Stadium       28
51                               Sheikh Zayed Stadium       29
52                                   St George's Park        7
53                         Subrata Roy Sahara Stadium       16
54                                    SuperSport Park       12
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                                   Wankhede Stadium       73
57                           Wankhede Stadium, Mumbai       57
58                   Zayed Cricket Stadium, Abu Dhabi        8

In [38]:
q("select batter,count(*) As delivery from deliveries group by batter order by delivery DESC;")

             batter  delivery
0           V Kohli      6942
1         RG Sharma      5561
2          S Dhawan      5483
3         DA Warner      4849
4         AM Rahane      4259
..              ...       ...
722     Sunny Gupta         1
723          U Kaul         1
724  V Pratap Singh         1
725   Y Prithvi Raj         1
726      YA Abdulla         1

[727 rows x 2 columns]

In [39]:
q("select match_winner,case when win_by_runs>50 then 'High runs' else 'Low runs' end as runs from matches;")

                     match_winner       runs
0           Kolkata Knight Riders  High runs
1             Sunrisers Hyderabad   Low runs
2          Rising Pune Supergiant   Low runs
3           Kolkata Knight Riders   Low runs
4                    Punjab Kings   Low runs
...                           ...        ...
1207  Royal Challengers Bangalore   Low runs
1208             Rajasthan Royals   Low runs
1209          Sunrisers Hyderabad   Low runs
1210               Gujarat Titans   Low runs
1211               Delhi Capitals   Low runs

[1212 rows x 2 columns]

In [40]:
q("select season, count(*) as match_number from matches group by season_id order by season_id;")

     season  match_number
0      2008            58
1      2009            57
2      2010            60
3      2011            73
4      2012            74
5      2013            76
6      2014            60
7      2015            59
8      2016            60
9      2017            59
10     2018            60
11     2019            60
12  2020/21            60
13     2021            60
14     2022            74
15     2023            74
16     2024            71
17     2025            74
18     2026            43

In [41]:
q("select venue, count(*) as match_number from matches group by venue order by match_number desc;")

                                                venue  match_number
0                                        Eden Gardens            77
1                                    Wankhede Stadium            73
2                               M Chinnaswamy Stadium            65
3                                    Feroz Shah Kotla            60
4                            Wankhede Stadium, Mumbai            57
5           Rajiv Gandhi International Stadium, Uppal            49
6                     MA Chidambaram Stadium, Chepauk            48
7                              Sawai Mansingh Stadium            47
8                 Dubai International Cricket Stadium            46
9            MA Chidambaram Stadium, Chepauk, Chennai            38
10                   Narendra Modi Stadium, Ahmedabad            37
11         Punjab Cricket Association Stadium, Mohali            35
12                               Sheikh Zayed Stadium            29
13                            Sharjah Cricket Stadium            28
14                              Eden Gardens, Kolkata            27
15                        Arun Jaitley Stadium, Delhi            27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...            26
17                   M Chinnaswamy Stadium, Bengaluru            24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...            23
19            Maharashtra Cricket Association Stadium            22
20                 Dr DY Patil Sports Academy, Mumbai            20
21                     Sawai Mansingh Stadium, Jaipur            19
22                         Dr DY Patil Sports Academy            17
23                          Brabourne Stadium, Mumbai            17
24                         Subrata Roy Sahara Stadium            16
25                 Rajiv Gandhi International Stadium            15
26                              M.Chinnaswamy Stadium            15
27                                          Kingsmead            15
28                               Arun Jaitley Stadium            14
29      Maharashtra Cricket Association Stadium, Pune            13
30  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...            13
31                                    SuperSport Park            12
32                       Sardar Patel Stadium, Motera            12
33  Punjab Cricket Association IS Bindra Stadium, ...            11
34             Saurashtra Cricket Association Stadium            10
35       Punjab Cricket Association IS Bindra Stadium            10
36  Maharaja Yadavindra Singh International Cricke...            10
37                                  Brabourne Stadium            10
38                             MA Chidambaram Stadium             9
39                             Holkar Cricket Stadium             9
40       Himachal Pradesh Cricket Association Stadium             9
41                   Zayed Cricket Stadium, Abu Dhabi             8
42                              New Wanderers Stadium             8
43                Barsapara Cricket Stadium, Guwahati             8
44                                   St George's Park             7
45                                           Newlands             7
46                 JSCA International Stadium Complex             7
47                                   Barabati Stadium             7
48   Shaheed Veer Narayan Singh International Stadium             6
49  Himachal Pradesh Cricket Association Stadium, ...             6
50  Punjab Cricket Association IS Bindra Stadium, ...             5
51                                      Nehru Stadium             5
52  Maharaja Yadavindra Singh International Cricke...             5
53                                         Green Park             4
54  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...             4
55       Vidarbha Cricket Association Stadium, Jamtha             3
56                              De Beers Diamond Oval             3
57                                       Buffalo Park             3
58                                    OUTsurance Oval             2

In [42]:
q("select venue, count(*) as match_number from matches group by venue order by match_number DESC limit 1;")

          venue  match_number
0  Eden Gardens            77

In [43]:
q("select venue, count(*) as match_number from matches group by venue order by match_number desc limit 5;")

                      venue  match_number
0              Eden Gardens            77
1          Wankhede Stadium            73
2     M Chinnaswamy Stadium            65
3          Feroz Shah Kotla            60
4  Wankhede Stadium, Mumbai            57

In [44]:
q("select batter, count(*) as delivery_count from deliveries group by batter order by delivery_count desc;")

             batter  delivery_count
0           V Kohli            6942
1         RG Sharma            5561
2          S Dhawan            5483
3         DA Warner            4849
4         AM Rahane            4259
..              ...             ...
722     Sunny Gupta               1
723          U Kaul               1
724  V Pratap Singh               1
725   Y Prithvi Raj               1
726      YA Abdulla               1

[727 rows x 2 columns]

In [45]:
q("select batter, count(*) as delivery_count from deliveries group by batter having count(*) > 1000 order by delivery_count desc;")

        batter  delivery_count
0      V Kohli            6942
1    RG Sharma            5561
2     S Dhawan            5483
3    DA Warner            4849
4    AM Rahane            4259
..         ...             ...
84  SO Hetmyer            1103
85   DJ Hussey            1101
86    MR Marsh            1098
87  TM Dilshan            1047
88   KM Jadhav            1012

[89 rows x 2 columns]

In [46]:
q("select season, count(*) as match_number from matches group by season_id having count(*) > 50 order by match_number desc;")

     season  match_number
0      2013            76
1      2025            74
2      2023            74
3      2022            74
4      2012            74
5      2011            73
6      2024            71
7      2021            60
8   2020/21            60
9      2019            60
10     2018            60
11     2016            60
12     2014            60
13     2010            60
14     2017            59
15     2015            59
16     2008            58
17     2009            57

In [47]:
q("select venue, count(*) as match_number from matches group by venue having count(*) > 20 order by match_number desc;")

                                                venue  match_number
0                                        Eden Gardens            77
1                                    Wankhede Stadium            73
2                               M Chinnaswamy Stadium            65
3                                    Feroz Shah Kotla            60
4                            Wankhede Stadium, Mumbai            57
5           Rajiv Gandhi International Stadium, Uppal            49
6                     MA Chidambaram Stadium, Chepauk            48
7                              Sawai Mansingh Stadium            47
8                 Dubai International Cricket Stadium            46
9            MA Chidambaram Stadium, Chepauk, Chennai            38
10                   Narendra Modi Stadium, Ahmedabad            37
11         Punjab Cricket Association Stadium, Mohali            35
12                               Sheikh Zayed Stadium            29
13                            Sharjah Cricket Stadium            28
14                              Eden Gardens, Kolkata            27
15                        Arun Jaitley Stadium, Delhi            27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...            26
17                   M Chinnaswamy Stadium, Bengaluru            24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...            23
19            Maharashtra Cricket Association Stadium            22

In [48]:
q("select batter, count(distinct match_id) as match_number from deliveries group by batter having count(distinct match_id) > 100 order by match_number desc;")

            batter  match_number
0        RG Sharma           270
1          V Kohli           268
2         MS Dhoni           241
3       KD Karthik           233
4         S Dhawan           221
5        RA Jadeja           201
6         SK Raina           200
7       RV Uthappa           197
8        AM Rahane           191
9        AT Rayudu           185
10       DA Warner           184
11       SV Samson           179
12  AB de Villiers           170
13      KA Pollard           168
14       MK Pandey           161
15        SA Yadav           159
16       YK Pathan           153
17       G Gambhir           151
18    F du Plessis           147
19       HH Pandya           147
20        KL Rahul           144
21         WP Saha           143
22        CH Gayle           141
23       SR Watson           141
24       DA Miller           140
25         SS Iyer           138
26        PA Patel           136
27      GJ Maxwell           134
28         RR Pant           131
29        AR Patel           129
30      JC Buttler           128
31    Yuvraj Singh           126
32      MA Agarwal           125
33       SP Narine           122
34    Shubman Gill           122
35    Ishan Kishan           121
36          N Rana           119
37       KH Pandya           118
38       Q de Kock           118
39      AD Russell           114
40        DJ Bravo           110
41     BB McCullum           109
42         M Vijay           105
43      MP Stoinis           104
44        V Sehwag           104
45        DJ Hooda           101

In [49]:
q("select season, count(distinct venue) as venue_count from matches group by season_id order by season_id;")

     season  venue_count
0      2008            9
1      2009            8
2      2010           13
3      2011           12
4      2012           12
5      2013           13
6      2014           13
7      2015           13
8      2016           11
9      2017           11
10     2018           10
11     2019            9
12  2020/21            3
13     2021            7
14     2022            6
15     2023           12
16     2024           13
17     2025           14
18     2026           11

In [50]:
q("select venue, count(*) as match_number from matches group by venue order by match_number desc limit 1;")

          venue  match_number
0  Eden Gardens            77

In [51]:
q("select venue, count(*) as match_number from matches group by venue order by match_number desc;")

                                                venue  match_number
0                                        Eden Gardens            77
1                                    Wankhede Stadium            73
2                               M Chinnaswamy Stadium            65
3                                    Feroz Shah Kotla            60
4                            Wankhede Stadium, Mumbai            57
5           Rajiv Gandhi International Stadium, Uppal            49
6                     MA Chidambaram Stadium, Chepauk            48
7                              Sawai Mansingh Stadium            47
8                 Dubai International Cricket Stadium            46
9            MA Chidambaram Stadium, Chepauk, Chennai            38
10                   Narendra Modi Stadium, Ahmedabad            37
11         Punjab Cricket Association Stadium, Mohali            35
12                               Sheikh Zayed Stadium            29
13                            Sharjah Cricket Stadium            28
14                              Eden Gardens, Kolkata            27
15                        Arun Jaitley Stadium, Delhi            27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...            26
17                   M Chinnaswamy Stadium, Bengaluru            24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...            23
19            Maharashtra Cricket Association Stadium            22
20                 Dr DY Patil Sports Academy, Mumbai            20
21                     Sawai Mansingh Stadium, Jaipur            19
22                         Dr DY Patil Sports Academy            17
23                          Brabourne Stadium, Mumbai            17
24                         Subrata Roy Sahara Stadium            16
25                 Rajiv Gandhi International Stadium            15
26                              M.Chinnaswamy Stadium            15
27                                          Kingsmead            15
28                               Arun Jaitley Stadium            14
29      Maharashtra Cricket Association Stadium, Pune            13
30  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...            13
31                                    SuperSport Park            12
32                       Sardar Patel Stadium, Motera            12
33  Punjab Cricket Association IS Bindra Stadium, ...            11
34             Saurashtra Cricket Association Stadium            10
35       Punjab Cricket Association IS Bindra Stadium            10
36  Maharaja Yadavindra Singh International Cricke...            10
37                                  Brabourne Stadium            10
38                             MA Chidambaram Stadium             9
39                             Holkar Cricket Stadium             9
40       Himachal Pradesh Cricket Association Stadium             9
41                   Zayed Cricket Stadium, Abu Dhabi             8
42                              New Wanderers Stadium             8
43                Barsapara Cricket Stadium, Guwahati             8
44                                   St George's Park             7
45                                           Newlands             7
46                 JSCA International Stadium Complex             7
47                                   Barabati Stadium             7
48   Shaheed Veer Narayan Singh International Stadium             6
49  Himachal Pradesh Cricket Association Stadium, ...             6
50  Punjab Cricket Association IS Bindra Stadium, ...             5
51                                      Nehru Stadium             5
52  Maharaja Yadavindra Singh International Cricke...             5
53                                         Green Park             4
54  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...             4
55       Vidarbha Cricket Association Stadium, Jamtha             3
56                              De Beers Diamond Oval             3
57                                       Buffalo Park             3
58                                    OUTsurance Oval             2

In [52]:
q("""select m.match_id,m.venue,v.city 
FROM matches m
JOIN venues v ON m.venue=v.venue""")

,match_id,venue,city
0,335982,M Chinnaswamy Stadium,Bangalore
1,1082591,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,1082592,Maharashtra Cricket Association Stadium,Pune
3,1082593,Saurashtra Cricket Association Stadium,Rajkot
4,1082594,Holkar Cricket Stadium,Indore
...,...,...,...
1311,1529282,"Arun Jaitley Stadium, Delhi",Delhi
1312,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
1313,1529284,"Wankhede Stadium, Mumbai",Mumbai
1314,1529285,"Narendra Modi Stadium, Ahmedabad",Ahmedabad
1315,1529286,"Sawai Mansingh Stadium, Jaipur",Jaipur

In [53]:
q("""SELECT d.batter,p.bat_style
FROM deliveries AS d
JOIN players AS p on p.player_name=d.batter;""")

            batter       bat_style
0       MN Samuels  Right hand Bat
1       MN Samuels  Right hand Bat
2       MN Samuels  Right hand Bat
3       MN Samuels  Right hand Bat
4       MN Samuels  Right hand Bat
...            ...             ...
288221      N Rana   Left hand Bat
288222      N Rana   Left hand Bat
288223      N Rana   Left hand Bat
288224   SU Parakh   Left hand Bat
288225   SU Parakh   Left hand Bat

[288226 rows x 2 columns]

In [54]:
q("""SELECT venue
FROM venues

EXCEPT
SELECT DISTINCT venue
FROM matches;""")

Empty DataFrame
Columns: [venue]
Index: []

In [55]:
q("select count(distinct batter) from deliveries where batter not in (select player_name from players);")

   count(distinct batter)
0                       0

In [56]:
q("select count(*) as TOTAL,sum(case when city isnull then 1 else 0 end) as Missing from matches;")

   TOTAL  Missing
0   1212       51

In [57]:
q("select count(*) as TOTAL,sum(case when city isnull then 1 else 0 end) as Missing from venues;")

   TOTAL  Missing
0     63        2

In [58]:
q("select count(*) as total, sum(case when city is null then 1 else 0 end) as as_null, sum(case when city = '' then 1 else 0 end) as empty from matches;")

   total  as_null  empty
0   1212       51      0

In [59]:
q("""SELECT COUNT (*) AS total, SUM (CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS nulls,
SUM(Case when city = '' THEN 1 ELSE 0 END) AS empty ,sum(case when trim(city)='' AND city<>'' THEN 1 ELSE 0 END)As spaces FROM matches;""")

   total  nulls  empty  spaces
0   1212     51      0       0